name: BridgeConnect
options:
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "15.0"
  createIntermediateGroups: true

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    exactVersion: 5.8.1
  RealmSwift:
    url: https://github.com/realm/realm-swift.git
    exactVersion: 10.45.2

targets:
  BridgeConnect:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/BridgeConnectApp
        name: BridgeConnectApp
    dependencies:
      - target: BridgeConnectKit
      - package: RealmSwift
    info:
      path: Sources/BridgeConnectApp/Info.plist
      properties:
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    settings:
      base:
        PRODUCT_NAME: BridgeConnect
        PRODUCT_BUNDLE_IDENTIFIER: com.kimnguyen.bridgeconnect
        DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES

  BridgeConnectKit:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/BridgeConnectKit
        name: BridgeConnectKit
    dependencies:
      - package: RealmSwift
      - package: Alamofire
    settings:
      base:
        PRODUCT_NAME: BridgeConnectKit
        PRODUCT_BUNDLE_IDENTIFIER: com.kimnguyen.bridgeconnect.kit
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: YES
