name: BridgeConnect
options:
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  useBaseInternationalization: true
  transitivelyLinkDependencies: true

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    exactVersion: 5.10.2
  RealmSwift:
    url: https://github.com/realm/realm-swift.git
    exactVersion: 10.54.2

targets:
  BridgeConnect:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/BridgeConnectApp
        name: BridgeConnectApp
    dependencies:
      - target: BridgeConnectKit
      - package: RealmSwift
      - package: Alamofire
      - sdk: GoogleMaps.framework
      - sdk: GooglePlaces.framework
    settings:
      base:
        PRODUCT_NAME: BridgeConnect
        PRODUCT_BUNDLE_IDENTIFIER: com.kimnguyen.bridgeconnect
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        FRAMEWORK_SEARCH_PATHS: $(inherited) "${PODS_ROOT}/GoogleMaps/Maps/Frameworks" "${PODS_ROOT}/GooglePlaces/Frameworks" "${PODS_XCFRAMEWORKS_BUILD_DIR}/GoogleMaps" "${PODS_XCFRAMEWORKS_BUILD_DIR}/GooglePlaces"
        OTHER_LDFLAGS: $(inherited) -ObjC
        ENABLE_BITCODE: YES
        BITCODE_GENERATION_MODE: bitcode
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchStoryboardName: ""
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "BridgeConnect needs your location to find resources near you."
        INFOPLIST_KEY_NSLocationAlwaysAndWhenInUseUsageDescription: "BridgeConnect needs your location to find resources near you."
        INFOPLIST_KEY_NSLocationAlwaysUsageDescription: "BridgeConnect needs your location to find resources near you."

  BridgeConnectKit:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/BridgeConnectKit
        name: BridgeConnectKit
    settings:
      base:
        PRODUCT_NAME: BridgeConnectKit
        PRODUCT_BUNDLE_IDENTIFIER: com.kimnguyen.bridgeconnect.kit
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        DEFINES_MODULE: YES
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        INSTALL_PATH: "@rpath"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        SKIP_INSTALL: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - package: RealmSwift
      - package: Alamofire
    settings:
      base:
        PRODUCT_NAME: BridgeConnectKit
        PRODUCT_BUNDLE_IDENTIFIER: com.kimnguyen.bridgeconnect.kit
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: YES
        DEFINES_MODULE: YES
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        INSTALL_PATH: "@executable_path/Frameworks"
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
